version: '3.7'
services:
  elasticsearch:
    hostname: docker-elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: docker-elasticsearch
    image: docker-elasticsearch
    volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  logstash:
    hostname: docker-logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: docker-logstash
    image: docker-logstash
    #volumes:
      #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      #- ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    hostname: docker-kibana
    build:
      context: ./kibana
      dockerfile: Dockerfile
    container_name: docker-kibana
    image: docker-kibana
    #volumes:
      #- ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
